apiVersion: apps/v1
kind: Deployment
metadata:
  name: ajibadeapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ajibadeapi
  template:
    metadata:
      labels:
        app: ajibadeapi
    spec:
      containers:
        - name: ajibadeapi
          image: ajibadeapiacr123.azurecr.io/ajibadeapi:latest
          ports:
            - containerPort: 8080
